### ISSUE TITLE
Chrome 90

### ISSUE THREAD

**Issue by arteze** [jsdelivr/www.jsdelivr.com#628]
In Linux I have a problem with the keyboard when I install the new Chrome, the accent marks in Spanish do not work, á é í or ú.

That's why I would like it to work for Chrome 90.
```js
Versión 90.0.4430.72 (Build oficial) (64 bits)
```
https://www.slimjet.com/chrome/google-chrome-old-version.php

```js
Object.hasOwn is not a function
```

**Comment by arteze** [comment]
Does that closure mean that they are not going to support old JS?

Did I need to give more details?

Aren't they going to use polyfills?

**Comment by jimaek** [comment]
Im sorry I dont know what you're talking about. Who is they? This is the repo for the website jsdelivr.com

**Comment by arteze** [comment]
When I update to the new Chrome I cannot write correctly in Spanish, because the accents do not work, this is why I wanted _jsdelivr.com_ to have compatibility for _Chrome 90_, the `Object.hasOwn` method has been there since _Chrome 93_.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn

I just downloaded Chrome 93 from the following link, right now I am going to restart the browser and use that version to see if it works jsdelivr.com and I will tell if it works or not.

https://bestim.org/chrome-93.html

The way I can think of to solve it is to create a polyfill or use a compatibility framework like jQuery (which I'm not sure would work).

https://github.com/zloirock/core-js/blob/master/packages/core-js/internals/has-own-property.js

At the moment I only get that error:

```js
_.js:462 Uncaught (in promise) TypeError: Object.hasOwn is not a function
    at Object.deepExtend (_.js:462)
    at search.js:21
deepExtend @ _.js:462
(anonymous) @ search.js:21
Promise.then (async)
(anonymous) @ search.html:68
setTimeout (async)
(anonymous) @ debounce.js:6
(anonymous) @ search.html:111
n @ observe.js:34
vh.dispatch @ Observer.js:46
_t @ runloop.js:104
xt @ runloop.js:110
end @ runloop.js:29
tl.handleChange @ Binding.js:68
Ri @ handleDomEvent.js:4
Xi @ Element.js:639
```

Code:

```js
deepExtend (out = {}, ...rest) {
	for (let i = 0; i < rest.length; i++) {
		let obj = rest[i];

		if (!obj) { continue; }

		for (let key in obj) {
			if (Object.hasOwn(obj, key)) {
				if (typeof obj[key] === 'object' && obj[key] !== null) {
					if (obj[key] instanceof Array) {
						out[key] = obj[key].slice(0);
					} else {
						out[key] = this.deepExtend(out[key], obj[key]);
					}
				} else {
					out[key] = obj[key];
				}
			}
		}
	}

	return out;
},
```

**Comment by arteze** [comment]
With _Chrome 93_ it worked perfectly, problem solved.

**Comment by MartinKolarik** [comment]
Hey, glad to see you already found a solution that works for you. This actually turned out to be an issue with our build process configuration as polyfills for recent features were meant to be automatically included - that was now fixed.

**Comment by arteze** [comment]
@MartinKolarik 
If I go back to Chrome 90, the problem still exists.

```js
Uncaught (in promise) TypeError: Object.hasOwn is not a function
    at Object.deepExtend (_.js:462)
    at search.js:21
```

__search.js__
```js
return npmIndex.search(parsed.query, options).then((response) => {
	return {
		response: _.deepExtend({}, response),
		query: queryString,
	};
});
```

**Comment by arteze** [comment]
My `userAgent`:

```js
navigator.userAgent
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36
```

**Comment by MartinKolarik** [comment]
@arteze please try now.

**Comment by arteze** [comment]
@MartinKolarik

It works correctly in Chrome 90,

I tried in previous versions and it has the problem that it does not recognize the spread operator (`...`).


```js
return {
	...labelsData,
	maxRangeValue,
	valueUnits,
	datasets,
};
```

**Comment by arteze** [comment]
In __Chrome 63__ it gives this error:
```js
Uncaught TypeError: Object.fromEntries is not a function
    at n (r-meta.html:19)
    at Array.isArray.t.filter.map.t (r-meta.html:17)
    at Array.map (<anonymous>)
    at n (r-meta.html:17)
    at Array.isArray.t.object.Object.fromEntries.Object.entries.map.t (r-meta.html:20)
    at Array.map (<anonymous>)
    at n (r-meta.html:19)
    at Array.isArray.t.filter.map.t (r-meta.html:17)
    at Array.map (<anonymous>)
    at n (r-meta.html:17)
```

**Comment by arteze** [comment]
It works correctly since __Chrome 75__.
